cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name
credentials:
  usernames:
    diegorm666:
      email: al2202000335@azc.uam.mx
      failed_login_attempts: 0
      logged_in: true
      name: Diego Ruiz
      password: $2b$12$oonB2p76NDK7zXuJNdJ7mOTRbMJ2yEE1l3p.emt98dG4TCIBmcYm.
      roles:
      - admin
    miriammora:
      email: miriam.mora@apptec.com.mx
      first_name: Miriam
      last_name: Mora
      logged_in: false
      password: $2b$12$Dq9efWRUvqfYrL55Arh.0ecg4IOMKVFUZJp3BTrsGXPkYkprr4BZ6 #miriamMora1512$ 
      password_hint: Provided
      roles:
      - user
    santiagotovar:
      email: santiago.tovar@apptec.com.mx
      first_name: Santiago
      last_name: Tovar
      logged_in: false
      password: $2b$12$4Vbq9jzVIaKdbxEHSpAf.OyKShQqdKi/5QZRvGq7Z5cpBiRe19EJa
      password_hint: Provided
      roles:
      - user
    victorreyes:
      email: victor.reyes@apptec.com.mx
      first_name: Victor
      last_name: Reyes Reyes
      logged_in: false
      password: $2b$12$6L0.Nz9bGSXyXN.nU63KNuEts.SwISizyYkr7dToIfB4Qef/BRnRq
      password_hint: Provided
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails: null
